### ISSUE TITLE
spamming spells while playing through ssh cause crush

### ISSUE THREAD

**Issue by lekto** [crawl/crawl#1152]
I was playing Deep Elf Fire Elementalist through ssh, this is a "bit" slow so I instead of casting spell and wait I tried to do it faster than game works (select spell, press f, select spell, press f…), every time I do this game crush with message:
ASSERT(!you.turn_is_over) in 'state.cc' at line 191 failed

platform: local tiles
version: 0.23.2
[crash-Lekto-20190919-131728.txt](https://github.com/crawl/crawl/files/3630992/crash-Lekto-20190919-131728.txt)

**Comment by lekto** [comment]
```
lekto@lapek ~ $ gdb crawl
GNU gdb (Gentoo 8.3 vanilla) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from crawl...
Reading symbols from /usr/lib/debug//usr/bin/crawl.debug...
(gdb) run
Starting program: /usr/bin/crawl 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff6c31700 (LWP 9990)]
[Detaching after fork from child process 9993]
ATTENTION: default value of option vblank_mode overridden by environment.
[New Thread 0x7ffff346c700 (LWP 10003)]
[New Thread 0x7fffebfff700 (LWP 10004)]
[New Thread 0x7ffff2c6b700 (LWP 10005)]
[New Thread 0x7ffff246a700 (LWP 10006)]
ASSERT(!you.turn_is_over) in 'state.cc' at line 191 failed.

Thread 1 "crawl" received signal SIGABRT, Aborted.
0x00007ffff7732491 in raise () from /lib64/libpthread.so.0
(gdb) backtrace 
#0  0x00007ffff7732491 in raise () from /lib64/libpthread.so.0
#1  0x000055555580c5eb in _BreakStrToDebugger (mesg=mesg@entry=0x7fffffffc590 "ASSERT(!you.turn_is_over) in 'state.cc' at line 191 failed.", 
    assert=true) at dbg-asrt.cc:808
#2  0x000055555580c794 in AssertFailed (expr=expr@entry=0x555555e73469 "!you.turn_is_over", file=file@entry=0x555555e732be "state.cc", 
    line=line@entry=191, text=text@entry=0x0) at dbg-asrt.cc:846
#3  0x0000555555cd6a2f in game_state::zero_turns_taken (this=<optimized out>) at state.cc:191
#4  0x0000555555c6d247 in cast_a_spell (check_range=check_range@entry=false, spell=spell@entry=SPELL_FLAME_TONGUE) at spl-cast.cc:859
#5  0x0000555555dcc559 in SpellRegion::handle_mouse (this=0x555556c8f870, event=...) at tilereg-spl.cc:71
#6  0x0000555555dcf928 in TilesFramework::handle_mouse (this=0x5555562069c0 <tiles>, event=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/g++-v9/bits/stl_vector.h:1040
#7  0x0000555555dd1c5a in TilesFramework::getch_ck (this=0x5555562069c0 <tiles>) at tilesdl.cc:791
#8  0x0000555555a3d612 in _getch_mul (rgetch=0x555555db5590 <m_getch()>) at macro.cc:739
#9  0x0000555555a4216a in getch_with_command_macros () at macro.cc:804
#10 0x0000555555de09b7 in _get_next_keycode () at main.cc:2386
#11 _get_next_cmd () at main.cc:2346
#12 _input () at main.cc:1123
#13 0x0000555555de1015 in _launch_game () at main.cc:468
#14 0x000055555576b36d in _launch_game_loop () at main.cc:377
#15 main (argc=<optimized out>, argv=<optimized out>) at main.cc:331
(gdb) 

```
