### ISSUE TITLE
webserver: unhandled error during rc-file save and missing import

### ISSUE THREAD

**Issue by alexjurkiewicz** [crawl/crawl#2382]
```
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: ERROR: Uncaught exception GET /socket (127.0.0.1)
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: HTTPServerRequest(protocol='http', host='crawl.project357.org', method='GET', uri='/socket', version='HTTP/1.1', remote_ip='127.0.0.1')
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: Traceback (most recent call last):
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:   File "/var/www/dcss/crawl-ref/source/webserver/webtiles/ws_handler.py", line 918, in on_message
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:     handler(**obj)
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:   File "/var/www/dcss/crawl-ref/source/webserver/webtiles/ws_handler.py", line 908, in set_rc
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:     with open(rcfile_path, 'wb') as f:
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: FileNotFoundError: [Errno 2] No such file or directory: '/var/dcss/gamedata/dcss-0.28/rc-files/chequers.rc'
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: During handling of the above exception, another exception occurred:
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: Traceback (most recent call last):
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:   File "/var/www/dcss/crawl-ref/source/webserver/venv/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:     result = callback(*args, **kwargs)
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:   File "/var/www/dcss/crawl-ref/source/webserver/webtiles/ws_handler.py", line 937, in on_message
Jan 26 20:48:16 ip-172-26-2-230 python[21764]:     if e.errno == errno.EAGAIN or e.errno == errno.ENOBUFS:
Jan 26 20:48:16 ip-172-26-2-230 python[21764]: NameError: name 'errno' is not defined
```

**Comment by rawlins** [comment]
Thanks, looks like before 76c8c3f4 this was getting implicitly imported by `from util import *`, hope there aren't other unusual error cases like this in there.
