### ISSUE TITLE
random crash (SIGABRT) while playing crawl-tiles on the Thunderdome Dungeon Sprint level

### ISSUE THREAD

**Issue by pabs3** [crawl/crawl#2519]
**PLATFORM and OS or BROWSER:**

crawl-tiles 2:0.28.0-1 from Debian bookworm.

**DCSS VERSION AND GAME INFORMATION:**

0.28.0

**DESCRIPTION:**

I got a random crash (SIGABRT) while playing the Thunderdome Dungeon Sprint level. I think I had an Octopode Fire Elementalist character with a few rings. After the crash there was a saved game in the menu, but it was from the start of the level instead of where I got up to. I didn't copy the save file unfortunately.

I don't have any way to reproduce this issue.

The gdb backtrace is included below and full gdb backtrace is attached and the morge crash file is attached.

The core dump will be available for the next two weeks and will be automatically removed from my system after that.

I use the crawl-tiles 2:0.28.0-1 Debian package maintained by @gsliepen and @trentbuck, SDL2 2.0.20+dfsg-2 on GNOME Wayland 42 on Debian bookworm.

If the info in this bug report isn't useful, please close the bug.

**BACKTRACE:**

```
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x000055a477ec161e in _BreakStrToDebugger(char const*, bool) [clone .constprop.0] (mesg=<optimized out>, assert=<optimized out>) at ./build-tiles/source/dbg-asrt.cc:813
#2  0x000055a477905415 in AssertFailed (expr=<optimized out>, file=0x55a477f28cf1 "mon-death.cc", line=1519, text=0x0) at ./build-tiles/source/dbg-asrt.cc:851
#3  0x000055a477b94aa6 in monster_die (mons=..., killer=KILL_DISMISSED, killer_index=27000, silent=true, wizard=<optimized out>, fake=<optimized out>) at ./build-tiles/source/mon-death.cc:1519
#4  0x000055a477b6973a in _monster_swaps_places (delta=..., mon=0x55a4781ef610 <env+258128>) at ./build-tiles/source/mon-act.cc:3118
#5  _monster_move (mons=<optimized out>) at ./build-tiles/source/mon-act.cc:3515
#6  0x000055a477b5a8fd in handle_monster_move (mons=<optimized out>) at ./build-tiles/source/mon-act.cc:1942
#7  0x000055a477b66959 in handle_monsters (with_noise=<optimized out>) at ./build-tiles/source/mon-act.cc:2339
#8  0x000055a477e3120f in world_reacts () at ./build-tiles/source/main.cc:2566
#9  0x000055a477e29987 in _input () at ./build-tiles/source/main.cc:1269
#10 0x000055a477e2bc05 in _launch_game () at ./build-tiles/source/main.cc:482
#11 0x000055a477780ec5 in _launch_game_loop () at ./build-tiles/source/main.cc:387
#12 main (argc=1, argv=0x7ffdf46adbf8) at ./build-tiles/source/main.cc:338
```

**EXTRA FILES:**

[crash-Utifot-20220406-160722.txt](https://github.com/crawl/crawl/files/8439416/crash-Utifot-20220406-160722.txt)

[Full gdb backtrace](https://github.com/crawl/crawl/files/8439288/tmp-crash-crawl-tiles.txt)

**Comment by rawlins** [comment]
I spent a bit of time on this and didn't succeed at replicating. The crash is on a somewhat rare codepath for foxfire (needs an enemy to attack it), and I had trouble forcing the scenario to happen, though it was happening enough that I don't think it's a common crash. From the log it sort of looks like a foxfire and a rat both got a shot at each other on the same turn? Which shouldn't happen. Also unsure if there's anything sprint-specific here.

**Comment by pabs3** [comment]
OK, sounds like the issue should be closed then?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
