### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GeneRickUsername** [crawl/crawl#3284]
**PLATFORM and OS or BROWSER:**

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

**EXTRA FILES:**
File: crawl/morgue/crash--20230906-130700.txt
Crash caused by signal #11: Segmentation fault

Version: Dungeon Crawl Stone Soup 0.30.0
Platform: unix
Bits: 64
Game mode: normal
Tiles: yes

Seed: 0, deterministic pregen: 1
Command line: crawl-tiles

RC options:
restart_after_game = true

Crash caused by signal #11: Segmentation fault

Obtained 21 stack frames.
crawl-tiles(+0x7a0cfb) [0x5bfa92d2ecfb]: 
crawl-tiles(+0x7cbd12) [0x5bfa92d59d12]: 
/lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7e8f4cef4d60]: 
/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x1033c2) [0x7e8f4d69e3c2]: 
/lib/x86_64-linux-gnu/libffi.so.7(+0x6d1d) [0x7e8f4be09d1d]: 
/lib/x86_64-linux-gnu/libffi.so.7(+0x6289) [0x7e8f4be09289]: 
/lib/x86_64-linux-gnu/libwayland-client.so.0(+0x92d2) [0x7e8f4c5ed2d2]: 
/lib/x86_64-linux-gnu/libwayland-client.so.0(+0x597a) [0x7e8f4c5e997a]: 
/lib/x86_64-linux-gnu/libwayland-client.so.0(wl_display_dispatch_queue_pending+0x6c) [0x7e8f4c5eb03c]: 
/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x101d09) [0x7e8f4d69cd09]: 
/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x4b6fc) [0x7e8f4d5e66fc]: 
/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x4b802) [0x7e8f4d5e6802]: 
crawl-tiles(+0x2b94c0) [0x5bfa928474c0]: 
crawl-tiles(+0x357e98) [0x5bfa928e5e98]: 
crawl-tiles(+0x5fb6a0) [0x5bfa92b896a0]: 
crawl-tiles(+0x3a44c5) [0x5bfa929324c5]: 
crawl-tiles(+0x3c8af3) [0x5bfa92956af3]: 
crawl-tiles(+0x2d0dbf) [0x5bfa9285edbf]: 
crawl-tiles(main+0x835) [0x5bfa927b8ea5]: 
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7e8f4cedfd0a]: 
crawl-tiles(_start+0x2a) [0x5bfa927bbaea]: 

Trying to run gdb.
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 7131]
[New LWP 7135]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007e8f4cf83747 in __GI___wait4 (pid=7136, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#0  0x00007e8f4cf83747 in __GI___wait4 (pid=7136, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
No locals.
#1  0x00005bfa92d2ebdf in ?? ()
No symbol table info available.
#2  0x00005bfa92d59d30 in ?? ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  0x00007e8f4d69e3c2 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#5  0x00007e8f4be09d1d in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
No symbol table info available.
#6  0x00007e8f4be09289 in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
No symbol table info available.
#7  0x00007e8f4c5ed2d2 in ?? () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#8  0x00007e8f4c5e997a in ?? () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#9  0x00007e8f4c5eb03c in wl_display_dispatch_queue_pending () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#10 0x00007e8f4d69cd09 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#11 0x00007e8f4d5e66fc in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#12 0x00007e8f4d5e6802 in ?? () from /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#13 0x00005bfa928474c0 in ?? ()
No symbol table info available.
#14 0x00005bfa928e5e98 in ?? ()
No symbol table info available.
#15 0x00005bfa92b896a0 in ?? ()
No symbol table info available.
#16 0x00005bfa929324c5 in ?? ()
No symbol table info available.
#17 0x00005bfa92956af3 in ?? ()
No symbol table info available.
#18 0x00005bfa9285edbf in ?? ()
No symbol table info available.
#19 0x00005bfa927b8ea5 in main ()
No symbol table info available.
[Inferior 1 (process 7130) detached]

Compilation info:
<<<<<<<<<<<
Compiled with GCC 8.3.0
Build platform: x86_64-linux-gnu
Platform: x86_64-linux-gnu
CFLAGS: -O2 -fdebug-prefix-map=/build/crawl-0.30.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects -pipe -DUSE_TILE -DUSE_TILE_LOCAL -DUSE_SDL -DUSE_GL -DUSE_FT -D_REENTRANT -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -isystem /usr/include/freetype2 -I/usr/include/libpng16 -isystem /usr/include/SDL2 -DWIZARD -DASSERTS -DPROPORTIONAL_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" -DMONOSPACED_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" -D_REENTRANT -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl" -DDATA_DIR_PATH="/usr/share/crawl/"
LDFLAGS: -rdynamic -fuse-ld=gold -O2 -fdebug-prefix-map=/build/crawl-0.30.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects 
>>>>>>>>>>>

Place info:
branch = 0, depth = 1

Level id: D:1
Level build method = ABSENT, level layout type  = ABSENT, absdepth0 = 0

Markers:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

Messages:
<<<<<<<<<<<<<<<<<<<<<<
Data directory '/usr/share/crawl/dat/' found.
Loading databases... Loading spells and features...

>>>>>>>>>>>>>>>>>>>>>>

Version history:
No version history (current version is 0.30.0)

Game state:

mouse_enabled: 0, waiting_for_command: 0, terminal_resized: 0
io_inited: 0, need_save: 0, saving_game: 0, updating_scores: 0:
seen_hups: 0, map_stat_gen: 0, type: 1, arena_suspended: 0

prev_cmd = CMD_NO_CMD
repeat_cmd = CMD_NO_CMD

Player:
{{{{{{{{{{{
Name:    []
Species: Yak
Job:     Unemployed

HP: 0/0; mods: 0/0
MP: 0/0; mod: 0
Stats: 0 (0) 0 (0) 0 (0)
Position: (0, 0) <OoB>, god: No God (0), turn_is_over: 0, banished: 0

Skills (mode: auto)
Name            | can_currently_train | train | training | level | points | progress
Fighting        |                     |   0   |     0    |    0  |      0 | 0/50
Short Blades    |                     |   0   |     0    |    0  |      0 | 0/50
Long Blades     |                     |   0   |     0    |    0  |      0 | 0/50
Axes            |                     |   0   |     0    |    0  |      0 | 0/50
Maces & Flails  |                     |   0   |     0    |    0  |      0 | 0/50
Polearms        |                     |   0   |     0    |    0  |      0 | 0/50
Staves          |                     |   0   |     0    |    0  |      0 | 0/50
Ranged Weapons  |                     |   0   |     0    |    0  |      0 | 0/50
Throwing        |                     |   0   |     0    |    0  |      0 | 0/50
Armour          |                     |   0   |     0    |    0  |      0 | 0/50
Dodging         |                     |   0   |     0    |    0  |      0 | 0/50
Stealth         |                     |   0   |     0    |    0  |      0 | 0/50
Shields         |                     |   0   |     0    |    0  |      0 | 0/50
Unarmed Combat  |                     |   0   |     0    |    0  |      0 | 0/50
Spellcasting    |                     |   0   |     0    |    0  |      0 | 0/50
Conjurations    |                     |   0   |     0    |    0  |      0 | 0/50
Hexes           |                     |   0   |     0    |    0  |      0 | 0/50
Summonings      |                     |   0   |     0    |    0  |      0 | 0/50
Necromancy      |                     |   0   |     0    |    0  |      0 | 0/50
Translocations  |                     |   0   |     0    |    0  |      0 | 0/50
Transmutations  |                     |   0   |     0    |    0  |      0 | 0/50
Fire Magic      |                     |   0   |     0    |    0  |      0 | 0/50
Ice Magic       |                     |   0   |     0    |    0  |      0 | 0/50
Air Magic       |                     |   0   |     0    |    0  |      0 | 0/50
Earth Magic     |                     |   0   |     0    |    0  |      0 | 0/50
Poison Magic    |                     |   0   |     0    |    0  |      0 | 0/50
Invocations     |                     |   0   |     0    |    0  |      0 | 0/50
Evocations      |                     |   0   |     0    |    0  |      0 | 0/50

Spell bugs:

Durations:

Attributes:

Mutations:

Inventory bugs:

Equipment:

}}}}}}}}}}}

Screenshot:
@

clua stack:

dlua stack:

Lua persistent data:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

Lua marker contents:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

**Comment by GeneRickUsername** [comment]
Crawl command line works fine.
